---
- name: create nginx Mount the directory
  file: path=/etc/nginx/ state=directory
- name: create nginx configure file
  copy: src=nginx.conf dest=/etc/nginx/
- name: docker run nginx
  shell: 'docker run --restart=always -it -d --net=host --name nginx -v /etc/nginx/nginx.conf:/etc/nginx/nginx.conf nginx:1.15.8'
